# site wide default variables
---
verbose: true
hostname: "example"
timezone: "America/Los_Angeles"
public_key: ansible.pub

ansible_user: ansible
ansible_uid: 1100
ansible_group: ansible
ansible_gid: 1100

admin_user: ian
admin_uid: 1101
admin_group: ian
admin_gid: 1101

zram_ratio: 0.8
cert_enabled: false
certbot_email: "name@example.com"

domain_app: 'blog'

siteFQDN: example.com
site_fqdn: "{{ siteFQDN }}"

certbot_domains: "{{ site_fqdn }},\
                  files.{{ site_fqdn }},\
                  git.{{ site_fqdn }},\
                  blog.{{ site_fqdn }},\
                  www.{{ site_fqdn }}"

app_git_repo: "https://git.example.com/name/{{ app_name }}.git"
file_server: "https://files.example.com"

# limit access to http apps from a local IP range with
# the option to limit specific apps when running https
limit_app: true
limit_source_ip: '192.168.1.0/24'

containers: true
containers_path: '/mnt/containers'

# munin
munin_username: 'example'
munin_password: 'example'

user_transmission: "example"
pass_transmission: "example"

pass_pihole: "example"

plex_claim: 'claim-0000000000000000000'

# ac backup
acsmFQDN: example.net
adminuser: user
assettouser: game_user
backup_path: '/home/game_user/backups'
backup_destination: '/mnt/backups'
backup_key: 'id_rsa'
