# zfs on centos

---
# https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html
# 2023-10-06: on Centos 9 Stream, use DKMS and not kABI
- name: add zfs key file
  ansible.builtin.rpm_key:
    key: https://raw.githubusercontent.com/zfsonlinux/zfsonlinux.github.com/master/zfs-release/RPM-GPG-KEY-openzfs-key2
    fingerprint: '7DC7 299D CF7C 7FD9 CD87 701B A599 FD5E 9DB8 4141'
    state: present

- name: add zfs repo
  ansible.builtin.dnf:
    name: https://zfsonlinux.org/epel/zfs-release-2-3.el9.noarch.rpm
    state: present
  register: zfs_install_state

- name: install zfs
  ansible.builtin.dnf:
    name:
      - epel-release
      - kernel-devel
      - zfs
    state: present

- name: lock kernel versions to zfs supported ones
  ansible.builtin.template:
    src: dnf_protected_zfs.j2
    dest: /etc/dnf/protected.d/zfs.conf
    owner: root
    group: root
    mode: '0644'

- name: add zfs module conf and restart if changed
  ansible.builtin.template:
    src: zfs.conf.j2
    dest: /etc/modules-load.d/zfs.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart system

- name: setup tank paths if mirror defined
  ansible.builtin.import_tasks: zfs_mirror.yml
  when: setup_zfs_mirror_paths|default(false) == true
