# rpi2b main.yml
---
- name: install udev rule for old style NIC name
  ansible.builtin.template:
    src: 10-network-device.rules.j2
    dest: /etc/udev/rules.d/10-network-device.rules
    owner: root
    group: root
    mode: '0640'
  notify: reload network Debian

  #   # disable bright red led
  #   # ref: https://forums.raspberrypi.com/viewtopic.php?t=338980
  #   dtparam=pwr_led_trigger=none
  #   # ref: https://github.com/raspberrypi/firmware/issues/1742
  #   #dtparam=pwr_led_trigger=default-on
  #   dtparam=pwr_led_activelow=off
