# timemachine timecapsule on rpi2b
# ref:
# https://ovechkin.xyz/blog/2021-12-13-using-raspberry-pi-for-time-machine
# https://stackoverflow.com/questions/44762488/non-interactive-samba-user-creation-via-ansible
---

- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_name }} account"

- name: install samba and avahi
  ansible.builtin.package:
    name:
      - samba
      - avahi-tools
    state: latest  # noqa package-latest
  when: not ansible_facts.machine == "armv7l"

- name: install samba and avahi
  ansible.builtin.package:
    name:
      - samba
      - avahi-daemon
    state: latest  # noqa package-latest
  when: ansible_facts.machine == "armv7l"

# why change firewall settings?
# kernel message ipv6 route cache full, nothing listed
# ref:
# https://bugzilla.redhat.com/show_bug.cgi?id=1813691
# https://serverfault.com/questions/902161/linux-host-randomly-stops-answering-ipv6-neighbor-solicitation-requests/907895#907895

- name: tweak filewall for avahi ipv6
  ansible.builtin.lineinfile:
    path: '/etc/firewalld/firewalld.conf'
    regexp: '^IPv6_rpfilter='
    line: 'IPv6_rpfilter=no'
  when: ansible_facts.machine == "armv7l"
  register: firewall_update

- name: reload firewalld if changes were made
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
  when: firewall_update.changed

# - name: set samba password for timecapsule account
#   ansible.builtin.command:
#     psudo cmd: sudo echo hunter2 | smbpasswd -s -a app_user

- name: setup directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  with_items:
    - "/mnt/hdd/{{ app_name }}"
    - "/mnt/hdd/{{ app_name }}/backups"

- name: update smb.conf file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
  register: smbconf_state

- name: open smb 445/tcp port
  ansible.builtin.firewalld:
    port: 445/tcp
    state: enabled
    permanent: true

- name: open mDNS port
  ansible.builtin.firewalld:
    port: 5353/udp
    state: enabled
    permanent: true

- name: reload samba
  ansible.builtin.systemd:
    name: smbd
    enabled: true
    state: reloaded
  when: smbconf_state.changed and ansible_facts.machine == "armv7l"

- name: reload samba
  ansible.builtin.systemd:
    name: smb
    enabled: true
    state: reloaded
  when: smbconf_state.changed and not ansible_facts.machine == "armv7l"

- name: install avahi service
  ansible.builtin.template:
    src: samba.service.j2
    dest: /etc/avahi/services/samba.service
    owner: root
    group: root
    mode: '0644'
  register: avahi_state

- name: reload avahi
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: true
    state: restarted
  when: avahi_state.changed
