# main.yml
# apple timecapsule
---

- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_name }} account"

- name: open smb 445/tcp port
  ansible.builtin.firewalld:
    port: 445/tcp
    state: enabled
    permanent: true

- name: open mDNS 5353/udp port
  ansible.builtin.firewalld:
    port: 5353/udp
    state: enabled
    permanent: true

- name: tweak filewall PIv6 filtering for avahi
  ansible.builtin.lineinfile:
    path: '/etc/firewalld/firewalld.conf'
    regexp: '^IPv6_rpfilter='
    line: 'IPv6_rpfilter=no'
  notify: reload firewall

- name: install timecapsule on rpi2b
  ansible.builtin.include_tasks: rpi2b.yml
  when: ansible_facts.nodename == "raspberrypi"

- name: install timecapsule on devbox
  ansible.builtin.include_tasks: devbox.yml
  when: ansible_facts.nodename == "devbox"
