# Update Playbook
---

### all hosts ###
- hosts: all
  gather_facts: true
  become: true

  roles:
    - common
    - sshd
    - zram

  handlers:
    - name: restart system
      ansible.builtin.reboot:

    - name: reload network
      ansible.builtin.systemd:
        name: network
        state: reloaded

    - name: reload network Debian
      ansible.builtin.systemd:
        name: networking
        state: restarted

    - name: reload sshd redhat
      ansible.builtin.service:
        name: sshd
        state: reloaded

    - name: reload ssh debian
      ansible.builtin.service:
        name: ssh
        state: reloaded
