# munin-client main.yml
---
- name: open port
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ app_port }}/tcp"

- name: install munin on centos stream 9
  ansible.builtin.include_tasks: centos_munin_install.yml
  when: ansible_os_family == "RedHat"

- name: install munin on rpi2b
  ansible.builtin.include_tasks: rpi2b_munin_install.yml
  when: ansible_os_family == "Debian"
