# rpi2b munin-node install
---

- name: install munin-node packages
  ansible.builtin.package:
    name:
      - munin-node
      - lm-sensors
      - liblwp-protocol-https-perl
      - libauthen-ntlm-perl
    state: latest

- name: add munin-node.conf template
  ansible.builtin.template:
    src: 'munin-node.conf.j2'
    dest: '/etc/munin/munin-node.conf'
    owner: munin
    group: munin
    mode: '0640'

- name: set hostname in munin.conf
  ansible.builtin.lineinfile:
    path: '/etc/munin/munin.conf'
    regexp: '^\[localhost.localdomain\]'
    line: '[{{ hostname }}]'

- name: add munin local.conf template
  ansible.builtin.template:
    src: 'munin_local_conf.j2'
    dest: '/etc/munin/munin-conf.d/local.conf'
    owner: munin
    group: munin
    mode: '0640'

- name: add munin plugins-conf template
  ansible.builtin.template:
    src: '10-plugins.j2'
    dest: '/etc/munin/plugin-conf.d/10-plugins'
    owner: root
    group: root
    mode: '0644'

- name: setup nginx status page for munin to pull from
  ansible.builtin.template:
    src: 'nginx_status.conf.j2'
    dest: '/etc/nginx/conf.d/nginx_status.conf'
    owner: root
    group: root
    mode: '0640'

- name: add plugin update script
  ansible.builtin.template:
    src: 'plugin_update.sh.j2'
    dest: '/etc/munin/plugin_update.sh'
    owner: munin
    group: munin
    mode: '0740'

- name: update enabled plugins
  ansible.builtin.command:
    cmd: /etc/munin/plugin_update.sh
  register: plugin_update_stat

- name: plugin update debug
  ansible.builtin.debug:
    msg: "{{ plugin_update_stat }}"
  when: verbose

- name: enable and start munin-node
  ansible.builtin.systemd:
    name: munin-node
    enabled: true
    state: restarted
