# requirements file
# e.x: ansible-galaxy install -r roles/requirements.yml
# https://galaxy.ansible.com/docs/using/installing.html
---
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
  - name: community.mysql
  - name: community.postgresql
  - name: containers.podman
