# pihole1 install
---
- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ clone_user }}"
    uid: "{{ clone_uid }}"
    group: "{{ clone_group }}"
    gid: "{{ clone_gid }}"
    comment: "{{ clone_comment }}"

- name: install pihole container
  ansible.builtin.include_role:
    name: pihole-main
    tasks_from: podman_pihole.yml
  vars:
    app_user: "{{ clone_user }}"
    app_group: "{{ clone_group }}"
    app_name: "{{ clone_name }}"
    app_port: "{{ clone_port }}"
  when: containers and not ansible_facts.machine == "armv7l"

- name: install pihole on rpi2b (armv7l)
  ansible.builtin.include_role:
    name: pihole-man
    tasks_from: pihole.yml
  vars:
    app_user: "{{ clone_user }}"
    app_group: "{{ clone_group }}"
    app_name: "{{ clone_name }}"
    app_port: "{{ clone_port }}"
  when: ansible_facts.machine == "armv7l"

- name: set forward proxy and ports
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
  vars:
    app_name: "{{ clone_name }}"
    app_port: "{{ clone_port }}"
  when: containers
