# certbot certs
---
- name: install renew script
  ansible.builtin.template:
    src: certbot_renew.sh
    dest: /usr/sbin/cerbot_renew.sh
    owner: root
    group: root
    mode: '0740'

- name: create cerbot renew logfile
  ansible.builtin.file:
    path: "/var/log/cerbot_renew.log"
    owner: root
    group: root
    state: touch

- name: add renew crontab
  become: true
  ansible.builtin.cron:
    name: "cerbot renew"
    day: 3
    hour: 3
    minute: 3
    job: "/usr/sbin/cerbot_renew.sh >> /var/log/cerbot_renew.log"

- name: ask certbot what domains have been registered
  become: true
  ansible.builtin.command:
    cmd: "certbot certificates"
  register: certbot_check

- name: output of certbot check
  ansible.builtin.debug:
    msg: "certbot certificates: {{ certbot_check }}"
  when: verbose

- name: check if cerbot certificate directory exists
  ansible.builtin.stat:
    path: '/etc/letsencrypt/live/{{ site_fqdn }}'
  register: certbot_dir

- name: stop nginx for certs if running
  ansible.builtin.service:
    name: nginx
    state: stopped
  when: not certbot_dir.stat.exists

- name: request letsencrypt certificates when they do not exist
  ansible.builtin.command:
    cmd: >
      certbot certonly
      -v
      --standalone
      --non-interactive
      --expand
      --agree-tos -m {{ certbot_email }}
      -d {{ certbot_domains }}

  when: not certbot_dir.stat.exists
  register: certbot_certonly_output

- name: output of certbot
  ansible.builtin.debug:
    msg: "certbot output {{ certbot_certonly_output }}"
  when: verbose
