# base webserver
---
- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

      ### different systems have different nginx uid gid ###
      # - name: create isolation user and group. Enable linger
      #   ansible.builtin.include_role:
      #     name: common
      #     tasks_from: create_user.yml
      #   vars:
      #     user: "{{ app_user }}"
      #     uid: "{{ app_uid }}"
      #     group: "{{ app_group }}"
      #     gid: "{{ app_gid }}"
      #     comment: "{{ app_comment }}"

- name: create directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  with_items:
    - "/etc/nginx/sites-available"

- name: add robots.txt
  ansible.builtin.copy:
    src: robots.txt
    dest: "{{ nginx_path }}/robots.txt"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: u=rwX,g=rX,o=rX

- name: open web ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  with_items:
    - 80/tcp
    - 443/tcp

- name: setup certs
  ansible.builtin.import_tasks: certbot.yml
  when: cert_enabled

- name: enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
