# base webserver
---
- name: install nginx on Debian
  ansible.builtin.package:
    name:
      - nginx
      - apache2-utils  # for htpasswd
    state: present
  when: ansible_os_family == 'Debian'

- name: install nginx on RedHat
  ansible.builtin.package:
    name:
      - nginx
      - httpd-tools  # for htpasswd
    state: present
  when: ansible_os_family == 'RedHat'

- name: create sites-available directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  with_items:
    - "/etc/nginx/sites-available"

- name: add robots.txt
  ansible.builtin.copy:
    src: robots.txt
    dest: "{{ nginx_path }}/robots.txt"
    owner: root
    group: root
    mode: '0644'

- name: open web ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  with_items:
    - 80/tcp
    - 443/tcp

- name: setup certs
  ansible.builtin.import_tasks: certbot.yml
  when: cert_enabled

- name: enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
