# pihole install
---
- name: create isolation user and group. Enable linger
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user.yml
  vars:
    user: "{{ app_user }}"
    uid: "{{ app_uid }}"
    group: "{{ app_group }}"
    gid: "{{ app_gid }}"
    comment: "{{ app_comment }}"

- name: install pihole container
  ansible.builtin.import_tasks: podman_pihole.yml
  when: containers and not ansible_facts.machine == "armv7l"

- name: check if pihole is installed on rpi2b
  ansible.builtin.stat:
    path: /etc/pihole
  register: pihole_path

- name: install pihole on rpi2b (armv7l)
  ansible.builtin.import_tasks: pihole.yml
  when: ansible_facts.machine == "armv7l" and not pihole_path.stat.exists

- name: set forward proxy and ports
  ansible.builtin.include_role:
    name: base-nginx
    tasks_from: forward_proxy.yml
    public: true
  when: containers
