# rpi2b transmission
---
- name: add sysctl 00-transmission.conf
  ansible.builtin.template:
    src: 00-transmission.conf.j2
    dest: /etc/sysctl.d/00-transmission.conf
    owner: root
    group: root
    mode: '0640'

- name: check if transmissioni-daemon is already installed on rpi2b
  ansible.builtin.stat:
    path: "/usr/local/bin/transmission-daemon"
  register: transmission_daemon

- name: install dependencies
  ansible.builtin.package:
    name:
      - cmake
      - libcurl4-openssl-dev
      - libssl-dev
    state: latest   # noqa package-latest
  when: not transmission_daemon.stat.exists

- name: download transmission 4
  ansible.builtin.get_url:
    url: https://github.com/transmission/transmission/releases/download/4.0.3/transmission-4.0.3.tar.xz      
    dest: /mnt/containers/tr/transmission-4.0.3.tar.xz
  when: not transmission_daemon.stat.exists

- name: untar transmission 4
  ansible.builtin.unarchive:
    src:  /mnt/containers/tr/transmission-4.0.3.tar.xz
    dest:  /mnt/containers/tr/transmission-4.0.3  
    remote_src: true  
  when: not transmission_daemon.stat.exists

    #  - name: build transmission 4
    #  cd /mnt/containers/tr/transmission-4.0.3
    #  mkdir build
    #  sudo cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    #  sudo make
    #  sudo make install
    #  when: not transmission_daemon.stat.exists

- name: create directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0775'
    state: directory
  with_items:
    - "{{ containers_path }}/{{ app_user }}/conf"
    - "{{ app_media }}/complete"
    - "{{ app_media }}/incomplete"
    - "{{ app_media }}/watch_folder"

- name: create logfile
  ansible.builtin.file:
    path: /var/log/transmission-daemon.log
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0640'
    state: touch

- name: install systemd service file
  ansible.builtin.template:
    src: transmission-daemon.service.j2
    dest: /etc/systemd/system/transmission-daemon.service
    owner: root
    group: root

- name: install transmission.json file
  ansible.builtin.template:
    src: templates/rpi2b-transmission-settings.json.j2
    dest: "{{ containers_path }}/{{ app_user }}/conf/settings.json"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0640'

- name: enable and start
  become: true
  ansible.builtin.systemd:
    daemon-reload: true
    no_block: true
    name: "transmission-daemon.service"
    enabled: true
    state: restarted
