# packages
---
- name: update packages to latest
  ansible.builtin.package:
    name: '*'
    state: latest  # noqa package-latest

- name: install epel-release
  ansible.builtin.package:  # noqa package-latest
    name: epel-release
    state: latest
  when: ansible_os_family == 'RedHat'

- name: add rpm fusion free key
  ansible.builtin.rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-9"
    fingerprint: "EDC0 0FE7 418C 9DF7 EF49  91A4 7403 EA33 2964 58F3"
    state: present
  when: ansible_os_family == 'RedHat'

- name: add rpm fusion nonfree key
  ansible.builtin.rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-9"
    fingerprint: "BB24 128A 4BB3 C335 2C0B  75A2 E417 4E6B AAB2 12EA"
    state: present
  when: ansible_os_family == 'RedHat'

- name: add rpm fusion free repo
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: add rpm fusion nonfree repo
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: install utility packages general
  ansible.builtin.package:
    name:
      - git
      - screen  # needs EPEL on centstream8
      - sysstat
      - zip
      - unzip
      - smartmontools
      - rsync
      - figlet
    state: latest  # noqa package-latest

- name: install utility packages rpi2b
  ansible.builtin.package:
    name:
      - acl  # ansible become_user
      - lsof
      - iotop
      - tree
    state: latest  # noqa package-latest
  when: ansible_os_family == 'Debian'

- name: drop package cache when working on the blog site
  ansible.builtin.command:
    cmd: dnf clean packages
  when: hostname == 'blog'

- name: install container tools
  ansible.builtin.package:
    name:
      - podman
    state: latest  # noqa package-latest
  when: containers

- name: set rootless storage path
  ansible.builtin.lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^# rootless_storage_path'
    line: 'rootless_storage_path =
      "{{ containers_path }}/$USER/storage"'
  when: containers and not ansible_os_family == "Debian"

    # - name: set cgroupsv2
    #   become: true
    #   ansible.builtin.command:
    #     cmd: grubby --update-kernel=/boot/vmlinuz-$(uname -r) --args='systemd.unified_cgroup_hierarchy=1'
    #   when: containers

- name: install letsencrypt certbot
  ansible.builtin.package:
    name: certbot
    state: latest  # noqa package-latest
  when: cert_enabled
