# rpi2b.yml
---
- name: install udev rule for old style NIC name
  ansible.builtin.template:
    src: 10-network-device.rules.j2
    dest: /etc/udev/rules.d/10-network-device.rules
    owner: root
    group: root
    mode: '0640'
  notify: reload network

- name: create folder structure in /mnt
  ansible.builtin.file:
    path: "{{ item.path }}/{{ item.dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - {path: /mnt, dir: hdd}
    - {path: /mnt, dir: ssd}
    - {path: /mnt/ssd, dir: transmission}
    - {path: /mnt/ssd, dir: containers}
    - {path: /mnt/hdd, dir: media}

- name: create links in /mnt
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    state: link
  loop:
    - {src: /mnt/hdd/media, dest: /mnt/media}
    - {src: /mnt/ssd/transmission, dest: /mnt/transmission}
    - {src: /mnt/ssd/containers, dest: /mnt/containers}

- name: add bash_aslises file
  ansible.builtin.template:
    src: rpi2b_bash_aliases
    dest: "/home/{{ user_account }}/.bash_aliases"
    owner: "{{ user_account }}"
    group: "{{ user_group }}" 
    mode: '0640'
