# rpi2b_plex.yml
---
- name: create directories for plex
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ containers_path }}/{{ app_name }}/config/Library/Application Support"
    - "{{ containers_path }}/{{ app_name }}/transcode"
    - "{{ media_path }}/audiobooks"
    - "{{ media_path }}/music"
    - "{{ media_path }}/movies"
    - "{{ media_path }}/tvshows"
    - "{{ media_path }}/racing"
    - "{{ media_path }}/yoga"
    - "{{ media_path }}/youtube"
    - "{{ media_path }}/lemans"

- name: check if plex is already installed
  ansible.builtin.stat:
    path: "/mnt/containers/plex/config/Library/Application Support/Plex Media Server"
  register: plex_path

- name: downlaod plexmediaserver
  ansible.builtin.get_url:
    url: "https://downloads.plex.tv/plex-media-server-new/1.32.1.6999-91e1e2e2c/debian/plexmediaserver_1.32.1.6999-91e1e2e2c_armhf.deb"
    dest: "/mnt/containers/plex/plexmediaserver.deb"
  when: not plex_path.stat.exists

- name: install plexmediaserver
  ansible.builtin.apt:
    deb: "/mnt/containers/plex/plexmediaserver.deb"
  when: not plex_path.stat.exists

- name: copy Plex Media Server folder to /mnt/containers/plex
  ansible.builtin.copy:
    src: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
    dest: "/mnt/containers/plex/config/Library/Application Support/"
    remote_src: true
  when: not plex_path.stat.exists

- name: remove Plex Media Server from var/lib before symlinking
  ansible.builtin.file:
    path: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server" 
    state: absent
  when: not plex_path.stat.exists

- name: link config
  ansible.builtin.file:
    src: "/mnt/containers/plex/config/Library/Application Support/Plex Media Server"
    dest: "/var/lib/plexmediaserver/Library/Application Support/"
    owner: root
    group: root
    state: link
  when: not plex_path.stat.exists
